-- First pass: Insert all WSOE members with their handicap indices
-- Using a CTE approach for efficiency

WITH wsoe_data AS (
  VALUES
    ('Tony Amedo', 13.1),
    ('Thomas Aphane', 11.9),
    ('Joe Asamoah', 2.3),
    ('Alfred Aygei', 12.7),
    ('Joshua Baganzi', 5),
    ('Amagyei Banson', 13.1),
    ('Abduragmaan Baulackey', 16.6),
    ('Phindile Bekwa', 18.5),
    ('Timo Bernhard', 10),
    ('Kiran Bhika', 15.3),
    ('Edwin Bogopa', 14.4),
    ('Pambili Booi', 10.4),
    ('Sonia Booth', 23.8),
    ('Mlungisi Cele', 14.1),
    ('Katlego Chabalala', 20.1),
    ('Daniel Chiwandamira', 10.1),
    ('Marvin Choma', 12.1),
    ('Andre de Jager', 0.3),
    ('Patrick Denga', 9.8),
    ('Ntombie Dengu', 8.5),
    ('Tebogo Dhlamini', 5.8),
    ('Elias Diale', 5.3),
    ('Bruce Diale B', 11.1),
    ('Oliver Dickson', 12.3),
    ('Boyo Diketso', 0),
    ('Abbey Dikgale', 23.9),
    ('Andi Dill', 0),
    ('Mmemezi Dlamini', 4.7),
    ('Bonga Dlamini ', 0),
    ('Mphilo Dlamini M', 11.5),
    ('Nathi Dlamini N', 14.1),
    ('Masande Dlulisa', 10.6),
    ('Tando Fani', 9.1),
    ('Marcellus Faustino', 11.6),
    ('Gastin Fenton', 15.2),
    ('Arthur Fernando', 0),
    ('Pro Fred', 0),
    ('Mondli Gabela', 8.2),
    ('Akbar Gani', 15),
    ('Bongani Godlwana', 10.1),
    ('Khumbulani Gumede', 7.1),
    ('Sipho Gura', 15.4),
    ('Mike Hannie', 0),
    ('Deane Hiine', 0.1),
    ('Linda Jakavula', 8.6),
    ('David Kau', 15.3),
    ('Diamond Kekana', 0),
    ('Alex Kensen', 0),
    ('Andile Keta', 0),
    ('Issac Kgafela', 0),
    ('Larry Kgatle', 18),
    ('Mokolokolo Kgopana', 0),
    ('Magz Khomane', 28),
    ('Sibusiso Khoza', 16.4),
    ('Vukani Khulu', 12.1),
    ('Ben Khumalo B', 19.7),
    ('Dingaan  Khumalo D', 4.6),
    ('Vukani Khumalo V', 7.7),
    ('Mogosi Khunwane', 10.6),
    ('Mauda King Coach', 0),
    ('Omolemo kitchin', 12.5),
    ('Lindiwe Klaaste', 21.8),
    ('Sico Kotumela', 15),
    ('Lunga Kupiso', 20),
    ('Leon Langa L', 11.2),
    ('Tumelo Langa T', 18.3),
    ('Maditsi Lekota', 0),
    ('Chimane Lelaka', 0),
    ('Sikhona Lembede', 11.5),
    ('Ntsieng Lenong', 0),
    ('Lethabo Leoto', 0),
    ('Tshepo Letsebe', 5.2),
    ('Peter Letsoalo', 10.3),
    ('Lungile Ludada', 11.1),
    ('Lee-John Maans', 0),
    ('Solly Mabandla', 0),
    ('Thembile Mabhaso', 13.9),
    ('Jomo Mabilo', 8.6),
    ('Sam Mabitsela', 0),
    ('Vulani Mabunda', 25.7),
    ('Treasure Mabunda', 0),
    ('Matlaba Machaka', 14.6),
    ('Trevor Machimana', 11.8),
    ('Fidelis Madavo', 14.4),
    ('Lungile Madela', 13.5),
    ('Thabiso Madiba', 4.1),
    ('Lebeko Madikgetla', 14.1),
    ('Tapiwa Mafana', 0),
    ('Francis Magero', 5.5),
    ('Sechele Magodielo', 5.8),
    ('Oscar Magudulela', 12.8),
    ('Thabo Mahlakwana', 5.3),
    ('Bongani Mahlangu B', 0),
    ('Thapelo Mahlangu T', 0),
    ('Vusi Mahlasela', 8),
    ('Ernest Mahlaule', 16),
    ('Thandisizwe Mahlutshana', 9.4),
    ('Xolani Mahote', 15.6),
    ('Votelwa Majola', 20.3),
    ('Luvuyo Makatesi', 15.6),
    ('Sipho Makhalema', 0),
    ('Edwin Makhothi', 0.8),
    ('Morgan Makhubela M', 0),
    ('Sipho Makhubela S', 0),
    ('Clifford Makoloane', 0),
    ('Tshepo Malatjie', 10.8),
    ('David Malaza', 24.3),
    ('Yanela Malusi', 21.8),
    ('Johannes Manamela', 4.1),
    ('Sonia Mangope', 23.1),
    ('Buntu Manitshana', 6.3),
    ('Nhlanhla Maphalala', 10.4),
    ('Mathew Maphuthu', 19.4),
    ('James Mapunda', 6.9),
    ('Alfred Maredi', 14.5),
    ('Elijah Maseko E', 17.2),
    ('Emmanuel Maseko EM', 9.9),
    ('Tebogo Masela', 0),
    ('Bafedile Masele', 10),
    ('Lyborn Mashava', 9.9),
    ('Kabelo Mashiko', 0),
    ('Leornard Masilela', 16.7),
    ('Sifiso Masina', 24.7),
    ('Thembinkosi Masinga', 11.3),
    ('Volvo Masubulele', 0),
    ('Eutycuss Mathebula', 10.9),
    ('Tumelo Matlakale', 7.5),
    ('Lwandiso Matoti', 16.2),
    ('Itumeleng Matsobane', 15.5),
    ('Nditsheni Matumba', 0),
    ('Mxolisi Mavumengwana', 21),
    ('Kwanele Mazibuko', 19.6),
    ('Joe Mazibuko J', 0),
    ('Jacques Mazima', 7.7),
    ('Christian Mbanga', 0),
    ('Thato MBHA', 0),
    ('Peter Mbugua', 0),
    ('Nathi Mdladla', 6.8),
    ('Ralph Mgijima', 16.1),
    ('Luvuyo Mgolodela', 16.1),
    ('Banele Mhlahlo', 6.2),
    ('Rivo Mhlari', 0),
    ('Helman Mkhalele', 10.7),
    ('Thulani Mkhize', 0),
    ('Boyce Mkhize B', 11),
    ('Vumani Mkhize V', 3),
    ('Herman Mmaudu', 0),
    ('Mogomotsi Mmutle', 0),
    ('Senzo Mncadi', 15.7),
    ('Sivuyile Mndawe', 11.6),
    ('Mukhouane Mocwana', 0.1),
    ('Bonolo Modise', 7.9),
    ('Goitsione Modise', 0),
    ('Shadrack Moephuli', 0),
    ('Obakeng Mofokeng', 18.9),
    ('Demist Mogafe', 7),
    ('Oscar Mogodiela', 0),
    ('Kenneth Mohlala', 10.4),
    ('Sam Mohlamanyane', 0),
    ('Percy Moiloa', 0),
    ('Peter Moima', 6.9),
    ('Teko Mojaki', 7.1),
    ('Fortune Mojapelo', 11.6),
    ('Greg Mojela', 8.4),
    ('Victor Mokgatle', 12.2),
    ('Jacob Mokhanda', 10.7),
    ('Elliot Mokoena', 10.2),
    ('Kenny Mokoka', 12.4),
    ('Lekopane Mokonopi', 20.7),
    ('Tsietsi Molai', 9.4),
    ('Tirisano Molamu', 15.3),
    ('Thabiso Molefe', 8.6),
    ('Boitumelo Moloko', 15.8),
    ('Chuene Moloto C', 4.6),
    ('Jeff Moloto J', 12.2),
    ('Connie Monageng', 11.4),
    ('Malesela Montja', 19.7),
    ('Moipone Morgan', 0),
    ('Letlhogonolo Moroeng', 8.8),
    ('Jan Morudu', 11.3),
    ('Willie Moshweou', 0),
    ('Chief Mosikara', 0),
    ('Tshepo Mosuwe', 16.4),
    ('Sean Motebang', 5.7),
    ('Simon Mothlasedi', 23.7),
    ('Philly Motsepe', 0),
    ('Xoliswa Motsohi', 18.7),
    ('Thabo Motswiane', 0),
    ('Emson Moyo', 10.2),
    ('Norman Moyo', 0),
    ('Olerato Mphake', 0),
    ('Bongani Mshibe', 0),
    ('Londani Msimang', 0),
    ('Liepollo Msimang', 0),
    ('Mandla Msimang M', 8.3),
    ('Sandile Mthiyane', 0),
    ('Patrick Mthombeni', 5.5),
    ('Reo Mugwira', 10.9),
    ('Zwido Mulaudzi', 7.5),
    ('Tuwani Mulaudzi T', 21),
    ('Shaun Musakada', 0),
    ('Lungile Mushwana', 8.4),
    ('Allen Mutono', 15.6),
    ('Given Mutshena', 10.8),
    ('Godfrey Mwiinga', -0.2),
    ('Mathew Mwiwa', 16.5),
    ('Skhumbuzo Mzele', 9.4),
    ('Peter Namingona', 0),
    ('Kingsley  Ncaba', 9.7),
    ('Smart Ncube', 3.8),
    ('Khumbu Ndebele', 11.4),
    ('Mpumelelo Ndimande', 15.6),
    ('Armstrong Ndlela', 0),
    ('Felix Ndlovu', 13.7),
    ('Gary Nemudzivhade', 0),
    ('Musa Nene', 6.9),
    ('Armstrong Ngcobo', 9.4),
    ('Cornelious Ngcukana', 19.8),
    ('Sakhiwe Ngobese', 6),
    ('Njabulo Ngubane', 6.6),
    ('Xolisa Ngwadla', 0),
    ('Ike Ngwena', 14.4),
    ('Wandile Nhlengethwa', 17.9),
    ('Tshediso Nkgoedi', 12.6),
    ('Tshepo Nkomo', 10.4),
    ('Ben Nkosi', 5.9),
    ('Siphiwe Nkula', 16.9),
    ('Owen Nkumane', 5.3),
    ('Thulani Nodangala', 3.7),
    ('Lindile Nojontsholo', 0.1),
    ('Fezile Nondonga', 0),
    ('Ngange Nongogo', 6.3),
    ('Ngange Nongoqo', 0),
    ('Manelisi Ntayiya', 20.2),
    ('Archie Ntim', 0),
    ('Micheli Ntsasa', 6.2),
    ('Thabiso Ntshingila', 0),
    ('Lukhanyo Ntshobodwana', 4.4),
    ('Mzwandile Ntuli', 0),
    ('Skhumbuzo Nxumalo', 16.1),
    ('Langa Nxumalo L', 11.1),
    ('Mzwandile Nxumalo M', 10.3),
    ('Nico Nyamupachito', 18.4),
    ('Litha Nyhonyha', 0),
    ('Vennah Ogounga', 5.4),
    ('Peter Paradza', 0),
    ('Malvern Patsanza', 0),
    ('Makgalaija Phokanoka', 17.4),
    ('Lester Pietersen', 6.5),
    ('David Oupa Pooe', 13.2),
    ('Nkululeko Poya', 9),
    ('David Rakotsoane', 13.2),
    ('Lesiba Ramashala', 13.1),
    ('Bathabile Ramatong', 11),
    ('Vishal Ramruthan', 0),
    ('Mpho Rantla', 0),
    ('Bongani (Bora) Rayi', 0),
    ('Mzwandile Riba', 13),
    ('Wendell Robinson', 11.8),
    ('John Rockson', 14.2),
    ('Mpho Seele', 16.4),
    ('Motlatjo Seema', 13.2),
    ('Tshepo Segone', 13.6),
    ('Thuso Segopolo', 15.3),
    ('Khutso Sekgota', 0),
    ('Khomotso Sekhabisa', 16.1),
    ('Lesedi Sennelo', 20.3),
    ('Joe Seoloane J', 19.8),
    ('Karabo Seoloane K', 5.5),
    ('Thabo Seopa', 0),
    ('Sanele Shabalala', 7),
    ('Mholi Shandu', 0),
    ('Cohen Shikwambane', 11.3),
    ('Theo Shiluvani', 10.7),
    ('Sean Shomang', 13.1),
    ('Vuyisile Sibaca', 24.2),
    ('Saider Sibanda', 17.8),
    ('Paul Sijadu', 16.6),
    ('Xolisa Sikobi', 0),
    ('Zakhele Simelane', 8.3),
    ('Jabu Sithole', 8),
    ('Mxolisi Siyonzana', 0),
    ('Gaba Tabane', 13.4),
    ('Awore Taigbenu', 0),
    ('Shelton Takara', 2.7),
    ('Jimmy Tau', 0),
    ('Mpho Tenyane', 16.9),
    ('Mothibi Thabeng', 17.4),
    ('Carl Thobejane', 8.1),
    ('Mpho Thohlang', 10.9),
    ('Zitha Thuki', 0),
    ('Mafika Thusi', 0),
    ('Andisiwe Tingo', 14.5),
    ('Lebo Tlomatsane', 7.8),
    ('Ditiro Tone', 0),
    ('Mzo Tshaka', 3.2),
    ('Yali Tshengiwe', 23.3),
    ('Thomas Tshikalange', 13.8),
    ('Malte Vosteen', 0.8),
    ('Richard Vries', 12.4),
    ('Patrick Wanjau', 0),
    ('Kevin Wotshela', 0),
    ('Nick Xolo', 0),
    ('Jerry Zungu', 10.6),
    ('Paul Counihan', 4.4),
    ('Itumeleng Oliphant', 10.7),
    ('Zweli Mabona', 16.7),
    ('Ashley Ramafoko', 8.2),
    ('Thabo Tselane', 5.3),
    ('Malethole Mathube', 0)
)
-- Insert members first
INSERT INTO members (member_name, club_id)
SELECT d.col1, 2
FROM wsoe_data d(col1, col2)
WHERE NOT EXISTS (
  SELECT 1 FROM members m 
  WHERE m.member_name = d.col1 AND m.club_id = 2
);

-- Now insert handicap indices
INSERT INTO member_handicap_indices (member_id, official_handicap_index, remmoho_handicap_index, effective_date, season)
SELECT m.member_id, NULL, d.col2, '2026-03-12', '2026'
FROM wsoe_data d(col1, col2)
JOIN members m ON m.member_name = d.col1 AND m.club_id = 2
WHERE NOT EXISTS (
  SELECT 1 FROM member_handicap_indices mhi 
  WHERE mhi.member_id = m.member_id AND mhi.season = '2026'
);
